# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.usage_log_summary import UsageLogSummary

class TestUsageLogSummary(unittest.TestCase):
    """UsageLogSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsageLogSummary:
        """Test UsageLogSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsageLogSummary`
        """
        model = UsageLogSummary()
        if include_optional:
            return UsageLogSummary(
                endpoint = '',
                request_count = 56,
                credits = 56
            )
        else:
            return UsageLogSummary(
        )
        """

    def testUsageLogSummary(self):
        """Test UsageLogSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
