# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.airports_full_api import AirportsFullApi


class TestAirportsFullApi(unittest.TestCase):
    """AirportsFullApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AirportsFullApi()

    def tearDown(self) -> None:
        pass

    def test_get_airports_full(self) -> None:
        """Test case for get_airports_full

        Get detailed airport information by code
        """
        pass


if __name__ == '__main__':
    unittest.main()
