# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.historic_flight_positions_light_api import HistoricFlightPositionsLightApi


class TestHistoricFlightPositionsLightApi(unittest.TestCase):
    """HistoricFlightPositionsLightApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HistoricFlightPositionsLightApi()

    def tearDown(self) -> None:
        pass

    def test_get_historic_flight_positions_light(self) -> None:
        """Test case for get_historic_flight_positions_light

        Get historical flight positions with basic details
        """
        pass


if __name__ == '__main__':
    unittest.main()
