# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.flight import Flight

class TestFlight(unittest.TestCase):
    """Flight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Flight:
        """Test Flight
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Flight`
        """
        model = Flight()
        if include_optional:
            return Flight(
                fr24_id = '',
                flight = '',
                callsign = '',
                lat = 1.337,
                lon = 1.337,
                track = 56,
                alt = 56,
                gspeed = 56,
                vspeed = 56,
                squawk = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source = '',
                hex = '',
                type = '',
                reg = '',
                painted_as = '',
                operating_as = '',
                orig_iata = 'ARN',
                orig_icao = 'ESSA',
                dest_iata = 'ARN',
                dest_icao = 'ESSA',
                eta = ''
            )
        else:
            return Flight(
        )
        """

    def testFlight(self):
        """Test Flight"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
