# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.flight_tracks_api import FlightTracksApi


class TestFlightTracksApi(unittest.TestCase):
    """FlightTracksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FlightTracksApi()

    def tearDown(self) -> None:
        pass

    def test_get_flights_tracks(self) -> None:
        """Test case for get_flights_tracks

        Get positional tracks for a specific flight
        """
        pass


if __name__ == '__main__':
    unittest.main()
