# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.flight_tracks import FlightTracks

class TestFlightTracks(unittest.TestCase):
    """FlightTracks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlightTracks:
        """Test FlightTracks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlightTracks`
        """
        model = FlightTracks()
        if include_optional:
            return FlightTracks(
                fr24_id = '',
                tracks = [
                    openapi_client.models.flight_tracks_tracks_inner.FlightTracks_tracks_inner(
                        timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        lat = 1.337, 
                        lon = 1.337, 
                        alt = 56, 
                        gspeed = 56, 
                        vspeed = 56, 
                        track = 56, 
                        squawk = '', 
                        callsign = '', 
                        source = '', )
                    ]
            )
        else:
            return FlightTracks(
        )
        """

    def testFlightTracks(self):
        """Test FlightTracks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
