# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.historic_flight_positions_full_api import HistoricFlightPositionsFullApi


class TestHistoricFlightPositionsFullApi(unittest.TestCase):
    """HistoricFlightPositionsFullApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HistoricFlightPositionsFullApi()

    def tearDown(self) -> None:
        pass

    def test_get_historic_flight_positions_full(self) -> None:
        """Test case for get_historic_flight_positions_full

        Get historical flight positions
        """
        pass


if __name__ == '__main__':
    unittest.main()
