# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.airport_detailed import AirportDetailed

class TestAirportDetailed(unittest.TestCase):
    """AirportDetailed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AirportDetailed:
        """Test AirportDetailed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AirportDetailed`
        """
        model = AirportDetailed()
        if include_optional:
            return AirportDetailed(
                name = 'Stockholm Arlanda Airport',
                iata = 'ARN',
                icao = 'ESSA',
                lon = 1.337,
                lat = 1.337,
                elevation = 150,
                country = {code=SE, name=SWEDEN},
                city = 'Stockholm',
                state = '',
                timezone = {name=Europe/Stockholm, offset=7200}
            )
        else:
            return AirportDetailed(
        )
        """

    def testAirportDetailed(self):
        """Test AirportDetailed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
