# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.airlines_light_api import AirlinesLightApi


class TestAirlinesLightApi(unittest.TestCase):
    """AirlinesLightApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AirlinesLightApi()

    def tearDown(self) -> None:
        pass

    def test_get_airlines_light(self) -> None:
        """Test case for get_airlines_light

        Get basic airline information by ICAO code
        """
        pass


if __name__ == '__main__':
    unittest.main()
