# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.airports_light_api import AirportsLightApi


class TestAirportsLightApi(unittest.TestCase):
    """AirportsLightApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AirportsLightApi()

    def tearDown(self) -> None:
        pass

    def test_get_airports_light(self) -> None:
        """Test case for get_airports_light

        Get basic airline information by code
        """
        pass


if __name__ == '__main__':
    unittest.main()
