# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.live_flight_positions_full_api import LiveFlightPositionsFullApi


class TestLiveFlightPositionsFullApi(unittest.TestCase):
    """LiveFlightPositionsFullApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LiveFlightPositionsFullApi()

    def tearDown(self) -> None:
        pass

    def test_get_live_flight_positions_full(self) -> None:
        """Test case for get_live_flight_positions_full

        Get real-time flight positions with detailed information
        """
        pass


if __name__ == '__main__':
    unittest.main()
