# coding: utf-8

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.live_flight_positions_light_api import LiveFlightPositionsLightApi


class TestLiveFlightPositionsLightApi(unittest.TestCase):
    """LiveFlightPositionsLightApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LiveFlightPositionsLightApi()

    def tearDown(self) -> None:
        pass

    def test_get_live_flight_positions_light(self) -> None:
        """Test case for get_live_flight_positions_light

        Get real-time flight positions
        """
        pass


if __name__ == '__main__':
    unittest.main()
