# coding: utf-8

# flake8: noqa

"""
    Flightradar24 API endpoints

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.airlines_light_api import AirlinesLightApi
from openapi_client.api.airports_full_api import AirportsFullApi
from openapi_client.api.airports_light_api import AirportsLightApi
from openapi_client.api.flight_tracks_api import FlightTracksApi
from openapi_client.api.historic_flight_positions_full_api import HistoricFlightPositionsFullApi
from openapi_client.api.historic_flight_positions_light_api import HistoricFlightPositionsLightApi
from openapi_client.api.live_flight_positions_full_api import LiveFlightPositionsFullApi
from openapi_client.api.live_flight_positions_light_api import LiveFlightPositionsLightApi
from openapi_client.api.usage_api import UsageApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.airline import Airline
from openapi_client.models.airport import Airport
from openapi_client.models.airport_detailed import AirportDetailed
from openapi_client.models.country import Country
from openapi_client.models.flight import Flight
from openapi_client.models.flight_positions import FlightPositions
from openapi_client.models.flight_tracks import FlightTracks
from openapi_client.models.flight_tracks_tracks_inner import FlightTracksTracksInner
from openapi_client.models.get_airlines_light400_response import GetAirlinesLight400Response
from openapi_client.models.get_airlines_light404_response import GetAirlinesLight404Response
from openapi_client.models.get_airports_full400_response import GetAirportsFull400Response
from openapi_client.models.get_airports_full404_response import GetAirportsFull404Response
from openapi_client.models.get_api_usage200_response import GetApiUsage200Response
from openapi_client.models.get_flights_tracks400_response import GetFlightsTracks400Response
from openapi_client.models.get_flights_tracks404_response import GetFlightsTracks404Response
from openapi_client.models.get_live_flight_positions_full200_response import GetLiveFlightPositionsFull200Response
from openapi_client.models.get_live_flight_positions_full400_response import GetLiveFlightPositionsFull400Response
from openapi_client.models.get_live_flight_positions_light200_response import GetLiveFlightPositionsLight200Response
from openapi_client.models.timezone import Timezone
from openapi_client.models.usage_log_summary import UsageLogSummary
